### ISSUE TITLE
Dataset not viewed due to continuous import notification

### ISSUE THREAD

**Issue by kgillette** [SCIInstitute/Seg3D#155]
There is a continuous import notification that pops up when loading data that does not go away. Cannot view any orientations or iso views at this point. Must change the view scene (pull the window wider) to make the data set viewable. There were large bars that showed for a view seconds when changing the window. 

![screen shot 2016-06-09 at 12 15 42 pm](https://cloud.githubusercontent.com/assets/12956701/15941268/8e7d0bb4-2e3c-11e6-9925-d85cf5c7b266.png)

**Comment by zaracay** [comment]
This occurs when importing a segmentation, data from single image, or data from image stack.

**Comment by aylakhan** [comment]
Rendered scene also goes away on auto-refresh and re-appears when GUI is perturbed.

**Comment by aylakhan** [comment]
Needs testing on Mac OS X

**Comment by krismz** [comment]
When running in debug mode, the following error appears 4 times (I think because I had 4 viewers open) after unpicturizing the viewers:
`OpenGL error 1286: invalid framebuffer operation`

This (probably) isn't the real fix, but commenting out the picturizing/unpicturizing of the viewers in ApplicationInterface.cc begin_progress and end_progress methods gets the rendered scene to redraw appropriately and the above errors go away.

**Comment by aylakhan** [comment]
Looks like this isn't a problem anymore.
