### ISSUE TITLE
Error with RBFInterface attempting to build under linux

### ISSUE THREAD

**Issue by bhallnz** [SCIInstitute/Seg3D#176]
I have attempted to compile Seg3D 2.3.2 and 2.4.0_rc2 under ubuntu 12.04 and  ubuntu 16.04 using gcc 4.8.3, 4.9.3 and 5.4.0.

It always fails on this error:

/usr/src/Seg3D-2.3.2/src/Application/Filters/Actions/ActionRadialBasisFunction.cc: In member function ‘virtual void RadialBasisFunction::RadialBasisFunctionAlgo::run_filter()’:
/usr/src/Seg3D-2.3.2/src/Application/Filters/Actions/ActionRadialBasisFunction.cc:209:55: error: ‘class RBFInterface’ has no member named ‘value’
           dstDataBlock->set_data_at( i, j, k, rbfAlgo.value[i][j][k] );

The build process is successfully cloning ImplicitFunction prior to the error.

Suggestions on how to resolve this would be welcome.

**Comment by djorlando24** [comment]
Hi, I have the same problem on Red Hat Enterprise. It seems that indeed RBFInterface.h does not specify a public variable called 'value'. It might be inherited from a header that's different on Linux to the Mac or Windows version, but I can't find where it comes from. In any case, ActionRadialBasisFunction.cc is trying to access the raw data stored in the class, which is exposed by the getRasterData() method. So I made a tweak to the code where it can call this function instead of trying to read the non-existent 'value'. This works on my system. I've not committed the change, I want the developers to look at it first. Here's the diff:

```
*** src/Application/Filters/Actions/ActionRadialBasisFunction.cc	2016-06-13 15:43:09.000000000 
209c209
<           dstDataBlock->set_data_at( i, j, k, rbfAlgo.value[i][j][k] );
---
>           dstDataBlock->set_data_at( i, j, k, rbfAlgo.getRasterData()[i][j][k] );
```

**Comment by aylakhan** [comment]
Master is building on Ubuntu now.

**Comment by djorlando24** [comment]
I can confirm that this is fixed. Thanks
